### ISSUE TITLE
Doesn't handle array notation query strings

### ISSUE THREAD

**Issue by jackmahoney** [mattsnider/jquery-plugin-query-parser#1]
Hey, thanks for making this plugin. Just pointing out that it doesn't handle multiple array notation in urls.

For instance

``` html
?filters[terms]=&filters[suitability][]=2&filters[suitability][]=4&filters[suitability][]=8&filters[vels]=
```

Sorry don't have a fix at the moment

**Comment by mattsnider** [comment]
I'll take a crack at trying to support these types of URLs, but I need a little clarification.

Are you expecting the above to parse into:

var filters = {
  suitability: [2, 4, 8],
  terms: undefined
};

If not, what do you expect?

Also, can you point me to where a query string like this would be generated in jQuery?
